spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    metadata-map:
      github:
        repo: PedroScheurer/marcal-store
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,circuit-breakers,circuit-breaker-events
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    defaults:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: [Serviço de descoberta que gerencia registro de outros serviços clientes]
    autor: [Pedro Konig Scheurer]