spring.application.name=greeting-service
server.port=8080

greeting-service.greeting=Ola
greeting-service.default-name=Mundo

spring.profiles.active=fr

management.endpoint.env.show-values=always

spring.config.import=optional:configserver:http://localhost:8888/

# Self Registration Pattern
eureka.client.service-url.default-zone=http://localhost:8761/eureka

# Ideal para ambientes containerizados
eureka.instance.prefer-ip-address=true

# Personalização do ID da instância
eureka.instance.instance-id=${spring.application.name}:${server.port}

eureka.instance.metadata-map.github.repo=PedroScheurer/microservices-atitus

# Health Check via Actuator
eureka.client.healthcheck.enabled=true

management.endpoints.web.exposure.include=health,info,metrics,circuit-breakers,circuit-breaker-events

management.endpoint.health.show-details=always

management.info.env.enabled=true

management.endpoint.health.probes.enabled=true

management.health.defaults.enabled=true

info.app.name=${spring.application.name}
info.app.description=[Serviço que expõe endoint de teste e busca configurações de profiles no config-service]
info.app.autor=[Pedro Konig Scheurer]
