server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:composite}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/PedroScheurer/marcal-store.git}
          default-label: main
          search-paths: configs
          clone-on-start: true
          force-pull: true
          timeout: 10
        native:
          search-locations: ${CONFIG_SEARCH_LOCATIONS:file:/app/configs}
        composite:
          - type: git
            uri: ${CONFIG_GIT_URI:https://github.com/PedroScheurer/marcal-store.git}
            default-label: main
            search-paths: configs
            clone-on-start: true
            force-pull: true
            timeout: 10
          - type: native
            search-locations: ${CONFIG_SEARCH_LOCATIONS:file:/app/configs}

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      github:
        repo: PedroScheurer/marcal-store
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,circuit-breakers,circuit-breaker,events
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    defaults:
      enabled: true
    configserver:
      enabled: false

info:
  app:
    name: ${spring.application.name}
    description: [Serviço que gerencia as configurações dos outros serviços via GitHub]
    autor: [Pedro Konig Scheurer]
