server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PedroScheurer/microservices-atitus.git
          default-label: main
          search-paths: 'configs'
          clone-on-start: true
          force-pull: true
        #native:
        #  search-locations: classpath:/config

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      github:
        repo: PedroScheurer/microservices-atitus
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,circuit-breakers,circuit-breaker,events
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    defaults:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: [Serviço que gerencia as configurações dos outros serviços]
    autor: [Pedro Konig Scheurer]